services:
  - type: web
    name: strata-scraper-api
    runtime: python
    rootDir: carnews-scraper/carnews
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0

  - type: web
    name: strata-dashboard
    runtime: static
    rootDir: dashboard
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
