-- Idea comparisons become filterable by analysis run (SM-73). A comparison
-- card's sources are only ever "as of" the last time idea_cluster_articles was
-- rebuilt for those articles, which happens per-article on every (re)analysis
-- (see idea_clustering.py's _replace_idea_clusters_for_article) - the same
-- "current state, not history" semantics articles.pipeline_run_id already
-- has. So a run-scoped comparison is generated by restricting candidate
-- articles to a.pipeline_run_id = the requested run (services/articles/
-- idea_comparisons.py), and cached per run scope the same way
-- project_trend_summaries does: run_id is '' rather than null for the
-- all-time view, so the natural-key unique constraint actually dedupes it.
alter table public.idea_comparisons
    add column if not exists run_id text not null default '';

alter table public.idea_comparisons
    drop constraint if exists idea_comparisons_unique_key;

alter table public.idea_comparisons
    add constraint idea_comparisons_unique_key unique (project_id, idea_cluster_id, run_id);
